### ISSUE TITLE
One-field curry

### ISSUE THREAD

**Issue by maciejhirsz** [pakastin/redom#14]
Gonna keep the Feedback issue for more broader design discussion.

What do you think about having these being equivalent:

```js
on({ click: callback })
on('click', callback)

prop({ src: url })
prop('src', url)

attr({ 'data-foo': 'bar' }) // this has to create a hashmap
attr('data-foo', 'bar')
```

❓ 

Implementation is pretty simple - you can check for `arguments.length` and return different functions from the curry.

**Comment by pakastin** [comment]
Sounds good! 👍

**Comment by maciejhirsz** [comment]
Since we don't have `prop` or `attr` (now that object maps are supported again), this issue can be closed?

**Comment by pakastin** [comment]
Fair enough! :)
