### ISSUE TITLE
el(tagName, ...args) & svg(tagName, ...args) should be more DRY..

### ISSUE THREAD

**Issue by pakastin** [pakastin/redom#16]
SVG elements don't allow writing to properties and namespace is needed when creating them. Otherwise they are pretty much the same.. There should be a way to share parts between el() and svg() to be more DRY..

**Comment by maciejhirsz** [comment]
The style prop handling is the most obvious candidate just skimming over the code. Gonna hack something there.

**Comment by pakastin** [comment]
I mean they should share more logic.. :/

**Comment by pakastin** [comment]
Maybe if we add a hidden `svg` property to SVG element and use that to force setAttribute or something..?

**Comment by maciejhirsz** [comment]
Well, the `el()` and `expand()` are broken apart, that should be useful...

**Comment by pakastin** [comment]
Yeah, but expand should somehow be able to tell the difference between HTMLElement and SVGElement and set properties/attributes or only attributes accordingly..

**Comment by maciejhirsz** [comment]
`expand()` is now an internal function that is only used as a bind to `el()` and `el.extend()` atm. The bindings can pass a boolean to `expand` much like it happens with `createElement`.

**Comment by pakastin** [comment]
Brilliant, I'll try that! 👍

**Comment by maciejhirsz** [comment]
Already on it ;)

**Comment by pakastin** [comment]
Ok 😊

**Comment by maciejhirsz** [comment]
All the argument passing form `el()` / `svg()` into expand is a lot of bloat. I'm still trying to figure out how to avoid it without losing performance.

**Comment by pakastin** [comment]
Cleverly passed that context there – I would have sent a new object every time :)

**Comment by pakastin** [comment]
Maybe I'll wait before merging if you're still working on something?

**Comment by pakastin** [comment]
Actually maybe it's easier if I add you as a collaborator and you can merge yourself ;)

**Comment by pakastin** [comment]
But maybe we should keep `master` synchronized with `npm` and make pull requests to `div` branch..? I can push releases to the `master` branch everytime I push npm versions. Ok?

**Comment by maciejhirsz** [comment]
Just don't merge yet 😅 .

I think I got a better solution - just committed, performance of cached elements got hit a bit, but it's still quite alright.

**Comment by maciejhirsz** [comment]
+147 −183 

Yep, better. And it appears to work :).

**Comment by pakastin** [comment]
You are collaborator now, check your email ;)

**Comment by maciejhirsz** [comment]
Aight, merged to `dev`!

**Comment by maciejhirsz** [comment]
`el()` got slightly faster, `el.extend()` got slightly slower.

```
Benching REDOM <div> with el()
7847ns per iteration (127431 ops/sec)

Benching REDOM <div> with precached elements
7032ns per iteration (142207 ops/sec)
```

I reckon that's quite reasonable as is.
