### ISSUE TITLE
idea! 💡

### ISSUE THREAD

**Issue by pakastin** [pakastin/redom#22]
Sorry for these constant changes, but I got an idea:
https://github.com/pakastin/redom/blob/idea/design.js

**Comment by pakastin** [comment]
Benefits:
1) View's template is a static single document fragment, which you can `cloneNode(true)` by a whole and `appendChild(clone)` to the app once.
2) There is true separation of concerns: 
  - template
  - initialization (getting references, settings event listeners which dispatches events upstream)
  - update
  - mount
  - ...

3) Using "query" to search quickly, instead of always using `querySelector`
4) You could still use `setChildren` to do if -logic to elements..
5) Lists also work as expected
6) Performance!

**Comment by maciejhirsz** [comment]
Going to be busy today so won't overly crazy on this just yet. Looks interesting though.

Did you considering adding a `<template>` tag support somehow? If we are deep cloning a fragment, and attaching references after, that might be an even better solution.

**Comment by pakastin** [comment]
Here's a draft example how document fragment could be created from the array:
https://github.com/pakastin/redom/blob/idea/src/view.js#L9-L13

And here's how `this.find` lookup creation could work: 
https://github.com/pakastin/redom/blob/idea/src/view.js#L26-L40

..based on hidden `query` values set by `el` (you can always fallback to querySelector if not found):
https://github.com/pakastin/redom/blob/idea/src/el.js#L6

**Comment by pakastin** [comment]
You could use querySelector for example:
```js
view('todo-app', {
  template: 'template.todo-app',
  ...
});
```

**Comment by pakastin** [comment]
..although then you miss the boost from the query lookup

**Comment by maciejhirsz** [comment]
Is `querySelector` that slow that we need to replace it? Looking up things is about 230ns last I checked.

Also if you intend to clone the fragment, the precached lookup references will point to the original fragment children instead of the instantiated view.

**Comment by pakastin** [comment]
The lookup is meant to point to the position map:
```js
{
  '.second': [1],
  '.second .third': [1, 2]
}
```
..etc
Then you can quickly search by for example: `this.childNodes[1].childNodes[2]`

**Comment by pakastin** [comment]
..although after init that doesn't make any difference – so `find` and `findAll` should only be on `init`'s context..

**Comment by pakastin** [comment]
The idea is that you don't change anything on init.

**Comment by maciejhirsz** [comment]
Aha, I see.

I was actually thinking about something similar in the context of using a `<template>` before, but IIRC regular `querySelector` was either faster or fast enough. I'll benchmark it, but basically:

```js
this.childNodes[1].childNodes[2] // 4 access points to DOM API
this.querySelector('foo') // 1 access point to DOM API
```

While querySelector has to technically do more work, it does all that work within the DOM API, without interfacing with V8, which does make it reasonably fast.

But again, I don't want to assume things, will benchmark.

**Comment by pakastin** [comment]
I think querySelector returns a static reference with ID's, but a live result with classNames/tagNames/etc.. So when you use the result it can change over time if I remember correctly.

**Comment by pakastin** [comment]
Oh, sorry: the other way around: getElementsByTagName returns a live NodeList and querySelectorAll returns static NodeList

**Comment by pakastin** [comment]
But `querySelector` and `querySelectorAll` are fine – there could be helpers for them though, so that `findAll` would return a regular array?

**Comment by maciejhirsz** [comment]
```js
var tree = el('div',
    el('.first'),
    el('.second',
        el('.inner')
    )
)

bench('get .inner with querySelector', function() {
    tree.querySelector('.inner');
});

bench('get .inner with childNodes indexing', function() {
    tree.childNodes[1].childNodes[0];
})
```

```
Benching get .inner with querySelector
177ns per iteration (5634437 ops/sec)

Benching get .inner with childNodes indexing
284ns per iteration (3527088 ops/sec)
```

And that's not even including getting the array from the hashmap and then looping over the array of indexing.

**Comment by pakastin** [comment]
Well, we can forget about that lookup then :D

**Comment by pakastin** [comment]
That makes things even more easier!

**Comment by maciejhirsz** [comment]
How about:

```js
view('.my-class', child1, child2, child3, {
  init () {

  },

  update (data) {

  },
});
```

**Comment by pakastin** [comment]
Wouldn't:
```js
view('.my-class', {
  template: [],
  ...
}
```
be more efficient, since you don't need to loop through x number of arguments?

**Comment by pakastin** [comment]
also if you want to use ES2015 modules:
```js
import { myClassDefinition } from './definitions';

view('.my-class', myClassdefinition);
```

**Comment by maciejhirsz** [comment]
> be more efficient, since you don't need to loop through x number of arguments?

You either iterate through arguments or array members, it's pretty much the same complexity :).

**Comment by pakastin** [comment]
What about: https://github.com/pakastin/redom/blob/idea/design.js

**Comment by pakastin** [comment]
Didn't work out that well: you can't clone components :/

But I like the new list design – works really well! 👍
