### ISSUE TITLE
[Question] Is custom event supported?

### ISSUE THREAD

**Issue by bigopon** [pakastin/redom#34]
I couldnt find support for custom event in source code. Wonder if its supported by redom ?

**Comment by pakastin** [comment]
Well, basically you can just [dispatchEvent](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) and add event listener..easy peasy! 😉

**Comment by pakastin** [comment]
I have actually thought about creating a simple helper for custom events, since I believe it's the best way to communicate upstream from views (using bubbling events). I keep you updated! 😎

**Comment by pakastin** [comment]
You can now dispatch custom events up and down the DOM:
```
import { el, mount, Dispatcher } from 'redom'

class A extends Dispatcher {
  constructor () {
    this.el = el('a')
    this.listener = this.listen('*', (type, data, event) => {
      console.log(type, data) // test, ok & test2, ok2
    })
    this.listener2 = this.listen('test', (data, event) => {
      console.log(data) // ok
    })
    setTimeout(() => {
      this.dispatchDown('test2', 'ok2')
    }, 1000)
  }
}
class B extends Dispatcher {
  constructor () {
    this.el = el('b')
    this.listener = this.listen('test2', (data) => {
      console.log(data) // ok2
    })
    setTimeout(() => {
      this.dispatch('test', 'ok')
    }, 1000)
  }
}
mount(a, b)
```

**Comment by pakastin** [comment]
Oh, and cancel listeners with:
```
this.listener.cancel()
```

**Comment by pakastin** [comment]
Sorry I had to remove Dispatcher, but you can use CustomEvent regularly.

Just call:
```js
this.el.dispatchEvent(new CustomEvent('my-event', { 
  detail: data, bubbles: true
}))
```

Here's another example:
https://youtu.be/iJ9hS54BRag?t=851

**Comment by pakastin** [comment]
I might do a micro library at some point. I decided it's something out of RE:DOM's scope – I want to keep the library as small as possible..
