### ISSUE TITLE
Browsersupport -> Readme

### ISSUE THREAD

**Issue by koljakutschera** [pakastin/redom#35]
Nice lib. Will try it out when i know browser-support. Did you test it?

Thank you.
K

**Comment by pakastin** [comment]
Thanks!
>= IE9 + all modern browsers

**Comment by pakastin** [comment]
Actually if you don't use `el.extend`, `svg.extend` or `list.extend` it should work <IE9 as well.

Here's the whole source code in one file: https://github.com/pakastin/redom/blob/master/dist/redom.js

Only ES5 stuff is `.bind` used in extends, otherwise it's just really basic JavaScript.

**Comment by pakastin** [comment]
Hope you like RE:DOM! If you have any questions, I'm happy to answer 😉
