### ISSUE TITLE
Event handling :>

### ISSUE THREAD

**Issue by katywings** [pakastin/redom#36]
Hey hey

I like new ways to develop in a modern way with minimal resources and therefore I enjoy the ideas behind RE:DOM

Every app needs some buttons and event handlers for them, I saw you allow to setup those bindings in `el('fu',{onclick: myFunc}, 'bar')`

Do they work when the fu element is rendered after some async magic? Got frustrated with jQuery lately which didnt allow late bindings on dynamic elements.

And is it possible to use anonymous functions?

**Comment by pakastin** [comment]
Hi!

`el` function returns the HTML element itself and all those properties are added synchronously here:
https://github.com/pakastin/redom/blob/master/src/el.js#L53

You can also use `addEventListener` if you like:
```js
var foo = el('foo', 'bar')
foo.addEventListener('click', myFunc)
```
Anonymous functions are fine too. ;)

**Comment by pakastin** [comment]
You should check out my talk from HelsinkiJS:
https://www.youtube.com/watch?v=0nh2EK1xveg

Hopefully that will clarify how things work under the hood.. 😎

If you have any further questions, I'm happy to help! Hope you like RE:DOM!

**Comment by katywings** [comment]
Hey hey :)

Wow, thats a fast answer! Ty <3 I will watch it :)

One more question though :D, are there custom events on el for after-render (to dom) and before-remove (from dom)? The idea behind those is to add animations for in/out

Toodaloo
Katja

**Comment by pakastin** [comment]
There are custom "events" for Views:
```js
class MyView {
  constructor () {
    this.el = el('foo', 'bar')
  }
  mounted () {
    console.log('Mounted to parent')
  }
  unmounted () {
    console.log('Unmounted from parent')
  }
}
```
..you can also use a regular function if you like:
```js
function MyView () {
  this.el = el('foo', 'bar')
  this.mounted = function () {
    console.log('mounted to parent')
  }
  this.unmounted = function () {
    console.log('unmounted from parent')
  }
}
```
Notice for now those functions get called when mounted to parent, not necessarily to the DOM. That will probably change in the near future.

**Comment by katywings** [comment]
Good evening

Ah okay, then I probably need to watch how RE:DOM evolves. I really like the design philosophy, but as it stands another render lib candidate will work out better.

(I need to render a complex tree with animations on pretty much any element and to instantiate a view for every element is just to much overhead) - i think..

I would love an Animation API for RE:DOM like this <3: http://maquettejs.org/docs/typedoc/interfaces/_maquette_.vnodeproperties.html#enteranimation

**Comment by pakastin** [comment]
Actually using `el('foo', { mounted: onMounted })` should work too, because the code doesn't check if the element is HTML element or component: 
https://github.com/pakastin/redom/blob/master/src/mount.js#L26

**Comment by pakastin** [comment]
You can also use middleware, like following: `el('foo', addEnterAnimation)`. enterAnimation gets called with the HTML element just created (`addEnterAnimation(element)`):
https://github.com/pakastin/redom/blob/master/src/el.js#L29

**Comment by katywings** [comment]
Really!?

Holy moly, now I need to watch the video anyway, c'mon Juha! XD

No seriously then I will make some tests and try it out :).

**Comment by pakastin** [comment]
I've done quite complex animations with RE:DOM:
http://codepen.io/pakastin/pen/aNYZee (the example is with FRZR though).

Notice how I'm animating elements on insert, reorder and remove ;)
Try resize the browser window and you'll see how responsive it is.
