### ISSUE TITLE
Idea for setChildren

### ISSUE THREAD

**Issue by katywings** [pakastin/redom#40]
How about allowing to use it without passing an array but just one component / el? Or do you consider this as an "unclean" approach? 

Personally I actually pretty much always try to allow `(item)` instead of `([item])` for my own API's :dancer:. 

I know `this.el.textContent = this.childComponentInstance.el` would work too, but its just not that nice ;)

**Comment by pakastin** [comment]
What is your use case? I'd recommend to use Router instead if those child's are changing..

**Comment by katywings** [comment]
Its really just something like this: `this.el.textContent = this.childComponentInstance.el`

Its just a cleaner way if setChildren could be used for such a thing too IMO ;)

**Comment by pakastin** [comment]
const setChild = (parent, child) => setChildren(parent, [child])

;)

I'm just kidding – I'll add the support for just one child!

**Comment by pakastin** [comment]
Hmm.. I'd suggest to just use `const setChild = (parent, child) => setChildren(parent, [child])` instead.. I wouldn't want to affect the performance of `setChildren`, because it's so mission critical (used in `List` as well).

**Comment by pakastin** [comment]
I think about adding that `setChild` method though..

**Comment by pakastin** [comment]
Fixed in [1.10.0](https://github.com/pakastin/redom/releases/tag/v1.10.0)!
