### ISSUE TITLE
List example on redom.js.org incorrect?

### ISSUE THREAD

**Issue by ejulen** [pakastin/redom#43]
Referring to the "Sync lists" part. Shouldn't the resulting HTML be the following?

```html
<body>
  <ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
  </ul>
</body>
```

Since this is what happens in the `update` method:

```js
this.el.textContent = `Item ${i}`;
```

**Comment by pakastin** [comment]
Thanks for letting know – fixed now! 😎 👍

**Comment by pakastin** [comment]
btw. We have a Slack channel #redom at [koodiklinikka.slack.com](koodiklinikka.slack.com), you can get an invite from [koodiklinikka.fi](koodiklinikka.fi), just write your email there and press enter ;)
