### ISSUE TITLE
router portion of api docs inconsistent

### ISSUE THREAD

**Issue by xz64** [pakastin/redom#44]
In the api docs, the App update function takes one destructured object (`{ section, data }`), but the actual instance passes two arguments to the update function (`'a', { val: 1}`).

```js
class App {
  constructor () {
    this.el = el('.app',
      this.content = router('.content', contentViews)
    );
  }

  update ({ section, data }) {
    this.content.update(section, data);
  }
}

const app = new App();

app.update('a', { val: 1 });
```

**Comment by pakastin** [comment]
Oh, it shouldn't be destructured. Thanks for letting know, I'll fix that! 😎👍

**Comment by pakastin** [comment]
Fixed now, thanks! 😎👍

ps. There's #redom channel in Slack, you can get an invite from koodiklinikka.fi, by just writing your email and pressing enter. Then join #redom 😉
