### ISSUE TITLE
setChildren a component with a list as component el (update: of course...) not working ^^

### ISSUE THREAD

**Issue by katywings** [pakastin/redom#45]
Hey hey Juha :)

# Danger: at the end is a Second Update, read that first please! :dancing_women:

# Issue

I am working on the todo example and found out the following interesting behaviour:

**Reduced example code: [Link](http://www.webpackbin.com/V112xCeUM)**

![jan 12 2017 7-20 pm - edited](https://cloud.githubusercontent.com/assets/4012401/21902655/0376fe82-d8fd-11e6-8562-10c5ad90085f.gif)

Every time I setChildren a [List](https://github.com/pakastin/redom/wiki/2.-API#listparentquery-childview-key-initdata) element which is the el of a component, the el will be toggle mounted.

---

My current workaround is to wrap the setChildren of the app-div in an `if(!inputElement.isMounted && !listElement.isMounted) { ... }`, but this workaround might not work in more complex scenarios...

After the workaround it looks like this:

![jan 12 2017 7-23 pm - edited 1](https://cloud.githubusercontent.com/assets/4012401/21908313/7a9f4b02-d913-11e6-84d0-7e6f8ea12387.gif)

---

Do you have an idea why that toggle happens on mutlible setChildren? 

---

# Update 1

Update: I tried a little bit around in the setChildren function and found a strange bugfix at the [Line](https://github.com/pakastin/redom/blob/master/src/setchildren.js#L18):

```js
    if (child.el) {
      // I noticed here, that child.el is not referenced to the dom element every second "setChildren", but just to the List, therefore to get the el it was needed to use child.el.el if defined :/
      if (child.el.el) {
        var childEl = child.el.el
      } else {
        var childEl = child.el
      }
    }
    else {
      var childEl = child
    }
```

Maybe you have an idea why the child.el is incorrectly referenced every second setChildren :)

# Update 2

:weary: I found out what I did wrong xD
```js
class MyList {
  constructor() {
    // This is not good
    this.el = list('ul', Li);
    this.el.update([ 1, 2, 3 ].map(i => 'Item ' + i));

    // Better would have been this:
    this.list = list('ul', Li);
    this.el = this.list.el
    this.el.update([ 1, 2, 3 ].map(i => 'Item ' + i));
  }
}
```

What I now dont understand is why the problem only happens every second setChildren :whale: 

But today I am too tired to figure it out...

**Comment by pakastin** [comment]
Hmm.. there is an extra check/fix for mounting a list to a component: https://github.com/pakastin/redom/blob/master/src/mount.js#L5

Your solution is also good!

I have no idea about that every second thing, sounds really weird..

**Comment by pakastin** [comment]
Btw. another way to create a list component is to use list.extend:

    class Td {
      constructor {
          this.el = el('td');
      }
      update (data) {
        this.el.textContent = data;
      }
    }

    const Tr = list.extend('tr', Td);
    const Table = list.extend('table', Tr);

    const table = new Table();
    table.update([ [ 1, 2, 3 ], [ 4, 5, 6 ], [ 7, 8, 9 ]);

**Comment by pakastin** [comment]
`List` is actually the thing, a view class. `list` is just a factory for it. `List.extend` or `list.extend` sets you up with a `List` view class with just the arguments prebound.

You could also use `list('table', List.bind(List, 'tr', Td));` but that's not pretty, right? 😄

Maybe this clarifies how it works under the hood: https://github.com/pakastin/redom/blob/master/src/list.js#L21

**Comment by pakastin** [comment]
You could *also* do:
```js
class Tr extends List {
  constructor () {
    super('tr', Td);
  }
  update (data) {
    super(data);
  }
}
```

**Comment by pakastin** [comment]
So List is already a view class. There is that fix for allowing element inside a view inside a view, but it's preferred to have just element inside a view 😎
