### ISSUE TITLE
List update child api idea :)

### ISSUE THREAD

**Issue by katywings** [pakastin/redom#47]
Sorry for my annoying looking-by :P, just working on the Todomvc and stumbled upon something:

https://github.com/pakastin/redom/wiki/2.-API#listparentquery-childview-key-initdata

In your list helper, isn't it not quite common that one needs the index of the current li item in the update function of the item? Would you consider something like this? (Adding a second parameter to the list update children behaviour) I think this would not be API breaking :).

```js
class Li {
  constructor () {
    this.el = el('li');
  }

  update (data, idx) {
    // idx is the index of this item in the [ 1, 2, 3 ] array
    this.el.textContent = data;
  }
}

const ul = list('ul', Li);

mount(document.body, ul)

ul.update([ 1, 2, 3 ].map(i => 'Item ' + i);
```

**Comment by pakastin** [comment]
It actually already does that, the documentation is lacking:
https://github.com/pakastin/redom/blob/master/src/list.js#L54

`update(item, index, data)`

😉
