### ISSUE TITLE
List update + clear

### ISSUE THREAD

**Issue by mietennet** [pakastin/redom#50]
first, i like that awesome lib!

my question is, after i do something like

list.update(data1)
list.update(data2)

data1 & data2 are in my list, fine... but how is the proper way to clear that list?

thanks

**Comment by mietennet** [comment]
list.update()

work well :)

**Comment by pakastin** [comment]
Yeah, that or `list.update([]);` 😉

**Comment by pakastin** [comment]
Btw. We have a Slack channel #redom @ koodiklinikka.slack.com

Just go to koodiklinikka.fi type your email and join to #redom 😎
