### ISSUE TITLE
the html cache

### ISSUE THREAD

**Issue by tunnckoCore** [pakastin/redom#71]
heya! im just scrolling over the code for endless time, and noticed one thing.

in the src/html file, when query is string u send it to memoizehtml if not exist in local cache object u just return the result of createElement, but u dont assign it to the cache.

so next time when the query argument is the same string it again will not get it from the cache.

ps: damn, i cant upload screenshot from android? huh..

**Comment by pakastin** [comment]
Really? Haha, what a mistake – I fix it ASAP! 🙂

**Comment by tunnckoCore** [comment]
yea! hahaha wat tha fast response!!

**Comment by pakastin** [comment]
Fixed and released (v2.6.4) – thank you! 👌

**Comment by tunnckoCore** [comment]
@pakastin AWESOME! :heart: :heart_eyes_cat:

**Comment by terkelg** [comment]
Nice one @tunnckoCore

**Comment by pakastin** [comment]
RE:DOM got faster! 💪😎👍
https://rawgit.com/krausest/js-framework-benchmark/41ccdbacbc9bf7d4b9d02ea97dc2a542836c1d16/webdriver-ts-results/table.html

**Comment by tunnckoCore** [comment]
haha, sweet! :sunglasses:

**Comment by pakastin** [comment]
It is (and was) number one (non-keyed) and number two (keyed) in startup time!

**Comment by tunnckoCore** [comment]
It's amazing how such small thing increased the wins :tada:
