### ISSUE TITLE
Unable to install redom with npm

### ISSUE THREAD

**Issue by Murchadha** [pakastin/redom#74]
Calling npm install redom fails stating its a dependency of itself

C:\dev\redom>npm install redom
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\apps\\nodejs\\node.exe" "C:\\apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "redom"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install redom as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\redom\npm-debug.log

**Comment by pakastin** [comment]
Hi!

Is your package name perhaps 'redom'..?
https://github.com/npm/npm/issues/12884

**Comment by Murchadha** [comment]
That was it thanks

**Comment by pakastin** [comment]
No worries! Hope you like RE:DOM, if you have any further questions don't hasitate to ask! 😉
