### ISSUE TITLE
Support for es6 modules in browsers

### ISSUE THREAD

**Issue by jens1o** [pakastin/redom#79]
This is currently not supported unfortunately...

I get this error in FF(with the flag enabled):
```
TypeError: global is undefined
```
in https://github.com/pakastin/redom/blob/0b719789106c93198632df4cd7d4ca7e5eefd5b0/dist/redom.js#L4

**Comment by pakastin** [comment]
Try https://redom.js.org/redom.es.js 😉

**Comment by jens1o** [comment]
No... That can't be the truth... I really checked I didn't do something wrong... I'm sorry! Thanks for this lib and the rapid response!

**Comment by pakastin** [comment]
No worries, have fun! 😎

**Comment by pakastin** [comment]
If you have any questions or ideas, just let me know!

**Comment by jens1o** [comment]
I'll do that, thanks!

**Comment by pakastin** [comment]
You're also welcome to our Slack channel:
https://redom.js.org/documentation/#support-feedback

**Comment by jens1o** [comment]
@pakastin Could you send me an invitation link? jenshausdorf@gmail.com I'm getting some error on the website, but I don't understand what it is trying to say.

**Comment by jens1o** [comment]
Thanks!

**Comment by pakastin** [comment]
There's now also https://redom.js.org/redom.es.min.js ;)

**Comment by jens1o** [comment]
Perfect, thanks!
